// Grundwortschatz A1–A2 — curated for Anker. Compact tuples keep the bundle small.

/** [gender, noun, plural ("-" = none), meaning, example, translation, notes?] */
export type NounRow = [string, string, string, string, string, string, string?];
/** [infinitive, meaning, forms, example, translation, notes?] */
export type VerbRow = [string, string, string, string, string, string?];
/** [word, meaning, pos, forms, example, translation, notes?] */
export type WordRow = [string, string, string, string, string, string, string?];

export const NOUNS_A1: NounRow[] = [
  ['der', 'Mann', 'Männer', 'man; husband', 'Der Mann liest die Zeitung.', 'The man is reading the newspaper.'],
  ['die', 'Frau', 'Frauen', 'woman; wife; Mrs', 'Die Frau arbeitet in Berlin.', 'The woman works in Berlin.'],
  ['das', 'Kind', 'Kinder', 'child', 'Das Kind spielt im Garten.', 'The child is playing in the garden.'],
  ['das', 'Mädchen', 'Mädchen', 'girl', 'Das Mädchen heißt Lena.', "The girl's name is Lena.", 'Diminutive -chen → always das.'],
  ['die', 'Familie', 'Familien', 'family', 'Meine Familie wohnt in München.', 'My family lives in Munich.'],
  ['pl', 'Eltern', '-', 'parents', 'Meine Eltern wohnen auf dem Land.', 'My parents live in the countryside.', 'Plural only.'],
  ['der', 'Vater', 'Väter', 'father', 'Mein Vater kocht gern.', 'My father likes to cook.'],
  ['die', 'Mutter', 'Mütter', 'mother', 'Meine Mutter ist Ärztin.', 'My mother is a doctor.'],
  ['der', 'Bruder', 'Brüder', 'brother', 'Mein Bruder ist älter als ich.', 'My brother is older than me.'],
  ['die', 'Schwester', 'Schwestern', 'sister', 'Meine Schwester studiert Medizin.', 'My sister studies medicine.'],
  ['der', 'Freund', 'Freunde', 'friend; boyfriend', 'Ich treffe heute einen Freund.', "I'm meeting a friend today."],
  ['die', 'Freundin', 'Freundinnen', '(female) friend; girlfriend', 'Meine Freundin kommt aus Wien.', 'My friend is from Vienna.'],
  ['pl', 'Leute', '-', 'people', 'Die Leute hier sind sehr nett.', 'The people here are very nice.', 'Plural only.'],
  ['der', 'Name', 'Namen', 'name', 'Wie ist Ihr Name?', 'What is your name?', 'Exception: ends in -e but masculine.'],
  ['das', 'Haus', 'Häuser', 'house', 'Das Haus hat einen großen Garten.', 'The house has a big garden.'],
  ['die', 'Wohnung', 'Wohnungen', 'apartment, flat', 'Die Wohnung ist hell und ruhig.', 'The apartment is bright and quiet.'],
  ['das', 'Zimmer', 'Zimmer', 'room', 'Mein Zimmer ist klein, aber gemütlich.', 'My room is small but cozy.'],
  ['die', 'Küche', 'Küchen', 'kitchen; cuisine', 'Wir essen in der Küche.', 'We eat in the kitchen.'],
  ['das', 'Bad', 'Bäder', 'bathroom; bath', 'Das Bad ist neben dem Schlafzimmer.', 'The bathroom is next to the bedroom.'],
  ['der', 'Tisch', 'Tische', 'table', 'Das Buch liegt auf dem Tisch.', 'The book is on the table.'],
  ['der', 'Stuhl', 'Stühle', 'chair', 'Setz dich auf den Stuhl!', 'Sit down on the chair!'],
  ['das', 'Bett', 'Betten', 'bed', 'Ich gehe um elf Uhr ins Bett.', 'I go to bed at eleven.'],
  ['die', 'Tür', 'Türen', 'door', 'Mach bitte die Tür zu!', 'Please close the door!'],
  ['das', 'Fenster', 'Fenster', 'window', 'Kannst du das Fenster öffnen?', 'Can you open the window?'],
  ['der', 'Schlüssel', 'Schlüssel', 'key', 'Ich finde meinen Schlüssel nicht.', "I can't find my key."],
  ['der', 'Kühlschrank', 'Kühlschränke', 'fridge', 'Der Kühlschrank ist leer.', 'The fridge is empty.'],
  ['die', 'Uhr', 'Uhren', "clock, watch; o'clock", 'Wie viel Uhr ist es?', 'What time is it?'],
  ['die', 'Stadt', 'Städte', 'city, town', 'Hamburg ist eine schöne Stadt.', 'Hamburg is a beautiful city.'],
  ['das', 'Land', 'Länder', 'country; countryside', 'Deutschland ist ein großes Land.', 'Germany is a big country.'],
  ['die', 'Straße', 'Straßen', 'street, road', 'Ich wohne in der Goethestraße.', 'I live on Goethestraße.'],
  ['die', 'Ecke', 'Ecken', 'corner', 'Die Bäckerei ist gleich um die Ecke.', 'The bakery is just around the corner.'],
  ['der', 'Bahnhof', 'Bahnhöfe', 'train station', 'Der Zug fährt um acht vom Bahnhof ab.', 'The train leaves the station at eight.'],
  ['der', 'Zug', 'Züge', 'train', 'Der Zug hat zehn Minuten Verspätung.', 'The train is ten minutes late.'],
  ['das', 'Auto', 'Autos', 'car', 'Wir fahren mit dem Auto nach Italien.', "We're driving to Italy."],
  ['der', 'Bus', 'Busse', 'bus', 'Ich fahre jeden Tag mit dem Bus.', 'I take the bus every day.'],
  ['das', 'Fahrrad', 'Fahrräder', 'bicycle', 'Im Sommer fahre ich mit dem Fahrrad zur Arbeit.', 'In summer I cycle to work.'],
  ['der', 'Flughafen', 'Flughäfen', 'airport', 'Wie komme ich zum Flughafen?', 'How do I get to the airport?'],
  ['die', 'Arbeit', 'Arbeiten', 'work; job', 'Die Arbeit beginnt um neun Uhr.', 'Work starts at nine.'],
  ['der', 'Beruf', 'Berufe', 'profession, job', 'Was sind Sie von Beruf?', 'What do you do for a living?'],
  ['die', 'Schule', 'Schulen', 'school', 'Die Kinder gehen noch zur Schule.', 'The children still go to school.'],
  ['die', 'Universität', 'Universitäten', 'university', 'Sie studiert an der Universität Heidelberg.', 'She studies at Heidelberg University.'],
  ['der', 'Lehrer', 'Lehrer', 'teacher (m)', 'Der Lehrer erklärt die Grammatik.', 'The teacher explains the grammar.'],
  ['der', 'Arzt', 'Ärzte', 'doctor (m)', 'Ich muss zum Arzt gehen.', 'I have to go to the doctor.'],
  ['das', 'Buch', 'Bücher', 'book', 'Das Buch ist sehr spannend.', 'The book is very exciting.'],
  ['die', 'Zeitung', 'Zeitungen', 'newspaper', 'Ich lese morgens die Zeitung.', 'I read the newspaper in the morning.'],
  ['der', 'Brief', 'Briefe', 'letter', 'Ich schreibe meiner Oma einen Brief.', "I'm writing my grandma a letter."],
  ['das', 'Handy', 'Handys', 'mobile phone', 'Mein Handy ist kaputt.', 'My phone is broken.', 'False friend: not "handy" in English.'],
  ['der', 'Computer', 'Computer', 'computer', 'Der Computer ist zu langsam.', 'The computer is too slow.'],
  ['die', 'Zeit', 'Zeiten', 'time', 'Hast du heute Zeit?', 'Do you have time today?'],
  ['der', 'Tag', 'Tage', 'day', 'Heute ist ein schöner Tag.', 'Today is a beautiful day.'],
  ['die', 'Woche', 'Wochen', 'week', 'Ich arbeite fünf Tage pro Woche.', 'I work five days a week.'],
  ['der', 'Monat', 'Monate', 'month', 'Der Kurs dauert drei Monate.', 'The course lasts three months.'],
  ['das', 'Jahr', 'Jahre', 'year', 'Ich lerne seit einem Jahr Deutsch.', "I've been learning German for a year."],
  ['die', 'Stunde', 'Stunden', 'hour; lesson', 'Der Film dauert zwei Stunden.', 'The film lasts two hours.'],
  ['die', 'Minute', 'Minuten', 'minute', 'Warte bitte fünf Minuten!', 'Please wait five minutes!'],
  ['der', 'Morgen', 'Morgen', 'morning', 'Am Morgen trinke ich Kaffee.', 'In the morning I drink coffee.', 'morgen (lowercase) = tomorrow.'],
  ['der', 'Abend', 'Abende', 'evening', 'Was machst du heute Abend?', 'What are you doing this evening?'],
  ['die', 'Nacht', 'Nächte', 'night', 'Gute Nacht und schlaf gut!', 'Good night and sleep well!'],
  ['das', 'Wochenende', 'Wochenenden', 'weekend', 'Am Wochenende gehe ich wandern.', 'At the weekend I go hiking.'],
  ['der', 'Urlaub', 'Urlaube', 'vacation, holiday', 'Im August haben wir Urlaub.', "We're on vacation in August."],
  ['der', 'Geburtstag', 'Geburtstage', 'birthday', 'Wann hast du Geburtstag?', 'When is your birthday?'],
  ['das', 'Wetter', '-', 'weather', 'Wie ist das Wetter heute?', "What's the weather like today?"],
  ['die', 'Sonne', 'Sonnen', 'sun', 'Die Sonne scheint den ganzen Tag.', 'The sun shines all day.'],
  ['der', 'Regen', '-', 'rain', 'Nach dem Regen kommt die Sonne.', 'After the rain comes the sun.'],
  ['der', 'Schnee', '-', 'snow', 'Im Januar liegt oft Schnee.', 'There is often snow in January.'],
  ['das', 'Essen', 'Essen', 'food; meal', 'Das Essen schmeckt sehr gut.', 'The food tastes very good.', 'Infinitive used as a noun → das.'],
  ['das', 'Frühstück', 'Frühstücke', 'breakfast', 'Das Frühstück ist um acht Uhr fertig.', 'Breakfast is ready at eight.'],
  ['das', 'Brot', 'Brote', 'bread', 'Ich kaufe frisches Brot beim Bäcker.', 'I buy fresh bread at the bakery.'],
  ['das', 'Brötchen', 'Brötchen', 'bread roll', 'Zum Frühstück esse ich zwei Brötchen.', 'I eat two rolls for breakfast.'],
  ['der', 'Käse', 'Käse', 'cheese', 'Magst du Käse?', 'Do you like cheese?', 'Exception: ends in -e but masculine.'],
  ['das', 'Fleisch', '-', 'meat', 'Ich esse kein Fleisch.', "I don't eat meat."],
  ['das', 'Gemüse', 'Gemüse', 'vegetables', 'Gemüse ist gesund.', 'Vegetables are healthy.', 'Ge- collective noun → das.'],
  ['das', 'Obst', '-', 'fruit', 'Ich esse jeden Tag Obst.', 'I eat fruit every day.'],
  ['der', 'Apfel', 'Äpfel', 'apple', 'Der Apfel ist rot und süß.', 'The apple is red and sweet.'],
  ['das', 'Wasser', '-', 'water', 'Ein Glas Wasser, bitte.', 'A glass of water, please.'],
  ['der', 'Kaffee', 'Kaffees', 'coffee', 'Ich trinke meinen Kaffee ohne Zucker.', 'I drink my coffee without sugar.'],
  ['der', 'Tee', 'Tees', 'tea', 'Möchtest du einen Tee?', 'Would you like a tea?'],
  ['die', 'Milch', '-', 'milk', 'Die Milch ist im Kühlschrank.', 'The milk is in the fridge.'],
  ['das', 'Bier', 'Biere', 'beer', 'Zwei Bier, bitte!', 'Two beers, please!'],
  ['der', 'Wein', 'Weine', 'wine', 'Dieser Wein kommt aus der Pfalz.', 'This wine comes from the Palatinate.'],
  ['das', 'Restaurant', 'Restaurants', 'restaurant', 'Wir gehen heute ins Restaurant.', "We're going to a restaurant today."],
  ['die', 'Rechnung', 'Rechnungen', 'bill, invoice', 'Die Rechnung, bitte!', 'The bill, please!'],
  ['das', 'Geld', 'Gelder', 'money', 'Ich habe kein Geld dabei.', "I don't have any money on me."],
  ['der', 'Preis', 'Preise', 'price; prize', 'Der Preis ist zu hoch.', 'The price is too high.'],
  ['der', 'Supermarkt', 'Supermärkte', 'supermarket', 'Der Supermarkt schließt um 20 Uhr.', 'The supermarket closes at 8 pm.'],
  ['der', 'Laden', 'Läden', 'shop', 'Der Laden an der Ecke ist sehr günstig.', 'The shop on the corner is very cheap.'],
  ['die', 'Kleidung', '-', 'clothing', 'Ich kaufe neue Kleidung für den Winter.', "I'm buying new clothes for the winter."],
  ['die', 'Hose', 'Hosen', 'trousers, pants', 'Die Hose ist zu lang.', 'The trousers are too long.', 'Singular in German!'],
  ['das', 'Hemd', 'Hemden', 'shirt', 'Er trägt ein weißes Hemd.', "He's wearing a white shirt."],
  ['der', 'Schuh', 'Schuhe', 'shoe', 'Ich brauche neue Schuhe.', 'I need new shoes.'],
  ['der', 'Kopf', 'Köpfe', 'head', 'Mir tut der Kopf weh.', 'My head hurts.'],
  ['die', 'Hand', 'Hände', 'hand', 'Wasch dir die Hände!', 'Wash your hands!'],
  ['das', 'Auge', 'Augen', 'eye', 'Sie hat blaue Augen.', 'She has blue eyes.', 'Exception: ends in -e but neuter.'],
  ['das', 'Krankenhaus', 'Krankenhäuser', 'hospital', 'Das Krankenhaus ist in der Nähe.', 'The hospital is nearby.'],
  ['die', 'Apotheke', 'Apotheken', 'pharmacy', 'Die Apotheke hat bis 18 Uhr geöffnet.', 'The pharmacy is open until 6 pm.'],
  ['die', 'Gesundheit', '-', 'health; bless you!', 'Gesundheit ist das Wichtigste.', 'Health is the most important thing.'],
  ['die', 'Sprache', 'Sprachen', 'language', 'Deutsch ist eine schöne Sprache.', 'German is a beautiful language.'],
  ['das', 'Wort', 'Wörter', 'word', 'Wie schreibt man dieses Wort?', 'How do you spell this word?'],
  ['der', 'Satz', 'Sätze', 'sentence', 'Bilde bitte einen Satz mit „weil“.', 'Please make a sentence with "weil".'],
  ['die', 'Frage', 'Fragen', 'question', 'Darf ich eine Frage stellen?', 'May I ask a question?'],
  ['die', 'Antwort', 'Antworten', 'answer', 'Die Antwort ist richtig.', 'The answer is correct.'],
  ['die', 'Adresse', 'Adressen', 'address', 'Wie ist deine Adresse?', "What's your address?"],
  ['der', 'Termin', 'Termine', 'appointment', 'Ich habe morgen einen Termin beim Arzt.', "I have a doctor's appointment tomorrow."],
  ['die', 'Idee', 'Ideen', 'idea', 'Das ist eine gute Idee!', "That's a good idea!"],
  ['das', 'Problem', 'Probleme', 'problem', 'Kein Problem!', 'No problem!'],
  ['die', 'Hilfe', 'Hilfen', 'help', 'Danke für deine Hilfe!', 'Thanks for your help!'],
  ['das', 'Geschenk', 'Geschenke', 'present, gift', 'Das Geschenk ist für dich.', 'The present is for you.'],
  ['das', 'Fest', 'Feste', 'celebration, festival', 'Das Fest beginnt um sieben.', 'The celebration starts at seven.'],
  ['das', 'Lied', 'Lieder', 'song', 'Dieses Lied höre ich jeden Tag.', 'I listen to this song every day.'],
  ['der', 'Film', 'Filme', 'film, movie', 'Der Film war total langweilig.', 'The film was totally boring.'],
  ['das', 'Spiel', 'Spiele', 'game; match', 'Das Spiel beginnt um halb vier.', 'The match starts at half past three.'],
  ['das', 'Hobby', 'Hobbys', 'hobby', 'Mein Hobby ist Fotografieren.', 'My hobby is photography.'],
  ['der', 'Garten', 'Gärten', 'garden', 'Im Garten blühen die Blumen.', 'The flowers are blooming in the garden.'],
  ['die', 'Blume', 'Blumen', 'flower', 'Ich schenke ihr Blumen.', "I'm giving her flowers."],
  ['der', 'Baum', 'Bäume', 'tree', 'Vor dem Haus steht ein alter Baum.', "There's an old tree in front of the house."],
  ['der', 'Hund', 'Hunde', 'dog', 'Der Hund bellt die ganze Nacht.', 'The dog barks all night.'],
  ['die', 'Katze', 'Katzen', 'cat', 'Die Katze schläft auf dem Sofa.', 'The cat is sleeping on the sofa.'],
  ['das', 'Tier', 'Tiere', 'animal', 'Welches Tier magst du am liebsten?', 'Which animal do you like best?'],
  ['das', 'Meer', 'Meere', 'sea', 'Im Sommer fahren wir ans Meer.', 'In summer we go to the sea.'],
  ['der', 'Berg', 'Berge', 'mountain', 'Wir wandern auf einen Berg.', "We're hiking up a mountain."],
  ['der', 'See', 'Seen', 'lake', 'Wir schwimmen im See.', 'We swim in the lake.', 'die See = the sea (poetic).'],
  ['die', 'Farbe', 'Farben', 'colour; paint', 'Welche Farbe hat dein Auto?', 'What colour is your car?'],
  ['die', 'Stimme', 'Stimmen', 'voice; vote', 'Sie hat eine schöne Stimme.', 'She has a beautiful voice.'],
  ['die', 'Nachricht', 'Nachrichten', 'message; (pl.) news', 'Ich habe deine Nachricht bekommen.', 'I got your message.'],
  ['die', 'Reise', 'Reisen', 'journey, trip', 'Gute Reise!', 'Have a good trip!'],
  ['das', 'Ticket', 'Tickets', 'ticket', 'Hast du schon ein Ticket gekauft?', 'Have you bought a ticket yet?'],
  ['die', 'Kirche', 'Kirchen', 'church', 'Die Kirche ist über 500 Jahre alt.', 'The church is over 500 years old.'],
  ['der', 'Nachbar', 'Nachbarn', 'neighbour (m)', 'Unser Nachbar ist sehr hilfsbereit.', 'Our neighbour is very helpful.', 'n-Deklination: den/dem/des Nachbarn.'],
];

export const VERBS_A1: VerbRow[] = [
  ['sein', 'to be', 'ist · war · ist gewesen', 'Ich bin heute sehr müde.', "I'm very tired today.", 'Irregular: bin, bist, ist, sind, seid, sind.'],
  ['haben', 'to have', 'hat · hatte · hat gehabt', 'Hast du heute Zeit?', 'Do you have time today?', 'habe, hast, hat, haben, habt, haben.'],
  ['werden', 'to become; will (future)', 'wird · wurde · ist geworden', 'Es wird langsam kalt.', "It's slowly getting cold.", 'du wirst, er wird.'],
  ['gehen', 'to go, to walk', 'geht · ging · ist gegangen', 'Wir gehen jetzt nach Hause.', "We're going home now."],
  ['kommen', 'to come', 'kommt · kam · ist gekommen', 'Woher kommst du?', 'Where are you from?'],
  ['machen', 'to do, to make', 'macht · machte · hat gemacht', 'Was machst du am Wochenende?', 'What are you doing at the weekend?'],
  ['sagen', 'to say', 'sagt · sagte · hat gesagt', 'Was hast du gesagt?', 'What did you say?'],
  ['sprechen', 'to speak', 'spricht · sprach · hat gesprochen', 'Sprechen Sie Deutsch?', 'Do you speak German?', 'e → i: du sprichst, er spricht.'],
  ['wohnen', 'to live (reside)', 'wohnt · wohnte · hat gewohnt', 'Ich wohne seit drei Jahren in Köln.', "I've been living in Cologne for three years."],
  ['arbeiten', 'to work', 'arbeitet · arbeitete · hat gearbeitet', 'Sie arbeitet bei einer Bank.', 'She works at a bank.', 'Stem ends in -t → du arbeitest, er arbeitet.'],
  ['lernen', 'to learn, to study', 'lernt · lernte · hat gelernt', 'Ich lerne jeden Tag zehn neue Wörter.', 'I learn ten new words every day.'],
  ['essen', 'to eat', 'isst · aß · hat gegessen', 'Wir essen um sieben zu Abend.', 'We have dinner at seven.'],
  ['trinken', 'to drink', 'trinkt · trank · hat getrunken', 'Trinkst du einen Kaffee mit mir?', 'Will you have a coffee with me?'],
  ['schlafen', 'to sleep', 'schläft · schlief · hat geschlafen', 'Hast du gut geschlafen?', 'Did you sleep well?'],
  ['fahren', 'to drive; to go (by vehicle)', 'fährt · fuhr · ist gefahren', 'Morgen fahren wir nach Berlin.', "Tomorrow we're going to Berlin."],
  ['sehen', 'to see', 'sieht · sah · hat gesehen', 'Siehst du das Schild dort?', 'Do you see the sign over there?'],
  ['lesen', 'to read', 'liest · las · hat gelesen', 'Ich lese gerade ein spannendes Buch.', "I'm reading an exciting book at the moment."],
  ['schreiben', 'to write', 'schreibt · schrieb · hat geschrieben', 'Schreib mir eine Nachricht!', 'Send me a message!'],
  ['hören', 'to hear, to listen', 'hört · hörte · hat gehört', 'Ich höre gern Musik.', 'I like listening to music.'],
  ['kaufen', 'to buy', 'kauft · kaufte · hat gekauft', 'Ich kaufe ein Geschenk für meine Mutter.', "I'm buying a present for my mother."],
  ['bezahlen', 'to pay', 'bezahlt · bezahlte · hat bezahlt', 'Kann ich mit Karte bezahlen?', 'Can I pay by card?'],
  ['brauchen', 'to need', 'braucht · brauchte · hat gebraucht', 'Ich brauche deine Hilfe.', 'I need your help.'],
  ['finden', 'to find; to think (opinion)', 'findet · fand · hat gefunden', 'Wie findest du den Film?', 'What do you think of the film?'],
  ['geben', 'to give', 'gibt · gab · hat gegeben', 'Gib mir bitte das Salz!', 'Please pass me the salt!', 'es gibt = there is/are.'],
  ['nehmen', 'to take', 'nimmt · nahm · hat genommen', 'Ich nehme die Suppe.', "I'll have the soup."],
  ['helfen', 'to help', 'hilft · half · hat geholfen', 'Kannst du mir helfen?', 'Can you help me?', 'helfen + Dativ (mir, dir, ihm…).'],
  ['wissen', 'to know (a fact)', 'weiß · wusste · hat gewusst', 'Ich weiß es nicht.', "I don't know.", 'ich weiß, du weißt, er weiß.'],
  ['kennen', 'to know (be familiar with)', 'kennt · kannte · hat gekannt', 'Kennst du meinen Bruder?', 'Do you know my brother?'],
  ['verstehen', 'to understand', 'versteht · verstand · hat verstanden', 'Das verstehe ich nicht.', "I don't understand that."],
  ['fragen', 'to ask', 'fragt · fragte · hat gefragt', 'Frag doch den Lehrer!', 'Why not ask the teacher!'],
  ['antworten', 'to answer', 'antwortet · antwortete · hat geantwortet', 'Bitte antworte mir schnell.', 'Please answer me quickly.', 'jemandem antworten (Dativ), auf eine Frage antworten.'],
  ['spielen', 'to play', 'spielt · spielte · hat gespielt', 'Die Kinder spielen Fußball.', 'The children are playing football.'],
  ['kochen', 'to cook', 'kocht · kochte · hat gekocht', 'Heute koche ich Spaghetti.', "Today I'm cooking spaghetti."],
  ['bleiben', 'to stay', 'bleibt · blieb · ist geblieben', 'Wir bleiben heute zu Hause.', "We're staying home today."],
  ['warten', 'to wait', 'wartet · wartete · hat gewartet', 'Ich warte auf den Bus.', "I'm waiting for the bus.", 'warten auf + Akkusativ.'],
  ['aufstehen', 'to get up', 'steht auf · stand auf · ist aufgestanden', 'Ich stehe um sieben Uhr auf.', 'I get up at seven.', 'Trennbar: auf|stehen.'],
  ['anrufen', 'to call (phone)', 'ruft an · rief an · hat angerufen', 'Ich rufe dich morgen an.', "I'll call you tomorrow.", 'Trennbar: an|rufen + Akkusativ.'],
  ['einkaufen', 'to go shopping', 'kauft ein · kaufte ein · hat eingekauft', 'Samstags kaufen wir auf dem Markt ein.', 'On Saturdays we shop at the market.', 'Trennbar: ein|kaufen.'],
  ['mögen', 'to like', 'mag · mochte · hat gemocht', 'Ich mag keine Tomaten.', "I don't like tomatoes.", 'ich möchte = I would like.'],
  ['können', 'can, to be able to', 'kann · konnte · hat gekonnt', 'Kannst du schwimmen?', 'Can you swim?'],
  ['müssen', 'must, to have to', 'muss · musste · hat gemusst', 'Ich muss jetzt leider gehen.', 'Unfortunately I have to go now.'],
  ['wollen', 'to want', 'will · wollte · hat gewollt', 'Wir wollen nach Spanien reisen.', 'We want to travel to Spain.'],
  ['dürfen', 'may, to be allowed to', 'darf · durfte · hat gedurft', 'Darf ich hier rauchen?', 'May I smoke here?'],
  ['öffnen', 'to open', 'öffnet · öffnete · hat geöffnet', 'Der Laden öffnet um neun Uhr.', 'The shop opens at nine.'],
  ['suchen', 'to look for', 'sucht · suchte · hat gesucht', 'Ich suche eine neue Wohnung.', "I'm looking for a new apartment."],
  ['zeigen', 'to show', 'zeigt · zeigte · hat gezeigt', 'Zeig mir deine Fotos!', 'Show me your photos!'],
  ['reisen', 'to travel', 'reist · reiste · ist gereist', 'Ich reise gern allein.', 'I like travelling alone.'],
  ['treffen', 'to meet', 'trifft · traf · hat getroffen', 'Wir treffen uns um acht vor dem Kino.', "We're meeting at eight in front of the cinema.", 'sich treffen = to meet up.'],
  ['gefallen', 'to please (= to like)', 'gefällt · gefiel · hat gefallen', 'Die Stadt gefällt mir sehr.', 'I really like the city.', 'The thing is the subject; the person is Dativ.'],
  ['denken', 'to think', 'denkt · dachte · hat gedacht', 'Ich denke oft an dich.', 'I often think of you.', 'denken an + Akkusativ.'],
];

export const WORDS_A1: WordRow[] = [
  ['gut', 'good; well', 'adjective', 'besser · am besten', 'Das Essen ist sehr gut.', 'The food is very good.'],
  ['schlecht', 'bad', 'adjective', 'schlechter · am schlechtesten', 'Das Wetter ist heute schlecht.', 'The weather is bad today.'],
  ['groß', 'big, tall', 'adjective', 'größer · am größten', 'Mein Bruder ist sehr groß.', 'My brother is very tall.'],
  ['klein', 'small, short', 'adjective', 'kleiner · am kleinsten', 'Die Wohnung ist leider zu klein.', 'Unfortunately the apartment is too small.'],
  ['alt', 'old', 'adjective', 'älter · am ältesten', 'Das Haus ist hundert Jahre alt.', 'The house is a hundred years old.'],
  ['neu', 'new', 'adjective', 'neuer · am neuesten', 'Ich habe ein neues Handy.', 'I have a new phone.'],
  ['jung', 'young', 'adjective', 'jünger · am jüngsten', 'Sie ist jünger als ich.', "She's younger than me."],
  ['schön', 'beautiful, nice', 'adjective', 'schöner · am schönsten', 'Was für ein schöner Tag!', 'What a beautiful day!'],
  ['teuer', 'expensive', 'adjective', 'teurer · am teuersten', 'München ist sehr teuer.', 'Munich is very expensive.'],
  ['billig', 'cheap', 'adjective', 'billiger · am billigsten', 'Das T-Shirt war billig.', 'The T-shirt was cheap.'],
  ['warm', 'warm', 'adjective', 'wärmer · am wärmsten', 'Heute ist es angenehm warm.', "It's pleasantly warm today."],
  ['kalt', 'cold', 'adjective', 'kälter · am kältesten', 'Im Winter ist es sehr kalt.', "It's very cold in winter."],
  ['schnell', 'fast, quick', 'adjective', 'schneller · am schnellsten', 'Der Zug ist schneller als das Auto.', 'The train is faster than the car.'],
  ['langsam', 'slow', 'adjective', 'langsamer · am langsamsten', 'Sprich bitte langsam!', 'Please speak slowly!'],
  ['müde', 'tired', 'adjective', 'müder · am müdesten', 'Ich bin heute sehr müde.', "I'm very tired today."],
  ['glücklich', 'happy', 'adjective', 'glücklicher · am glücklichsten', 'Sie ist sehr glücklich.', "She's very happy."],
  ['lecker', 'tasty, delicious', 'adjective', 'leckerer · am leckersten', 'Der Kuchen ist lecker!', 'The cake is delicious!'],
  ['einfach', 'simple, easy', 'adjective', 'einfacher · am einfachsten', 'Die Aufgabe ist ganz einfach.', 'The task is really easy.'],
  ['schwer', 'difficult; heavy', 'adjective', 'schwerer · am schwersten', 'Deutsch ist gar nicht so schwer.', "German isn't that hard at all."],
  ['wichtig', 'important', 'adjective', 'wichtiger · am wichtigsten', 'Das ist sehr wichtig.', "That's very important."],
  ['richtig', 'right, correct', 'adjective', '', 'Das ist richtig.', "That's correct."],
  ['falsch', 'wrong', 'adjective', '', 'Die Antwort ist leider falsch.', 'Unfortunately the answer is wrong.'],
  ['früh', 'early', 'adjective', 'früher · am frühesten', 'Ich stehe gern früh auf.', 'I like getting up early.'],
  ['spät', 'late', 'adjective', 'später · am spätesten', 'Es ist schon spät.', "It's already late."],
  ['gemütlich', 'cozy, comfortable, relaxed', 'adjective', 'gemütlicher · am gemütlichsten', 'Das Café ist sehr gemütlich.', 'The café is very cozy.', 'No exact English equivalent — warm, snug and relaxed.'],
  ['nett', 'nice, kind', 'adjective', 'netter · am nettesten', 'Die Nachbarn sind sehr nett.', 'The neighbours are very nice.'],
  ['krank', 'ill, sick', 'adjective', 'kränker · am kränksten', 'Ich bin krank und bleibe im Bett.', "I'm sick and staying in bed."],
  ['fertig', 'finished, ready', 'adjective', '', 'Bist du fertig?', 'Are you ready?'],
  ['voll', 'full', 'adjective', 'voller · am vollsten', 'Der Bus ist total voll.', 'The bus is totally full.'],
  ['leer', 'empty', 'adjective', 'leerer · am leersten', 'Die Flasche ist leer.', 'The bottle is empty.'],
  ['heute', 'today', 'adverb', '', 'Heute habe ich frei.', 'I have the day off today.'],
  ['morgen', 'tomorrow', 'adverb', '', 'Bis morgen!', 'See you tomorrow!', 'der Morgen = the morning.'],
  ['gestern', 'yesterday', 'adverb', '', 'Gestern war ich im Kino.', 'Yesterday I was at the cinema.'],
  ['jetzt', 'now', 'adverb', '', 'Ich habe jetzt keine Zeit.', "I don't have time now."],
  ['immer', 'always', 'adverb', '', 'Er kommt immer zu spät.', "He's always late."],
  ['oft', 'often', 'adverb', '', 'Wir gehen oft ins Theater.', 'We often go to the theatre.'],
  ['manchmal', 'sometimes', 'adverb', '', 'Manchmal koche ich für Freunde.', 'Sometimes I cook for friends.'],
  ['nie', 'never', 'adverb', '', 'Ich trinke nie Alkohol.', 'I never drink alcohol.'],
  ['schon', 'already', 'adverb', '', 'Bist du schon fertig?', 'Are you finished already?'],
  ['noch', 'still; yet', 'adverb', '', 'Ich wohne noch bei meinen Eltern.', 'I still live with my parents.'],
  ['gern', 'gladly; (to like doing)', 'adverb', 'lieber · am liebsten', 'Ich tanze gern.', 'I like dancing.', 'verb + gern = to like doing something.'],
  ['auch', 'also, too', 'adverb', '', 'Ich komme auch mit.', "I'm coming along too."],
  ['nur', 'only', 'adverb', '', 'Ich habe nur zehn Euro.', 'I only have ten euros.'],
  ['vielleicht', 'maybe, perhaps', 'adverb', '', 'Vielleicht regnet es morgen.', "Maybe it'll rain tomorrow."],
  ['leider', 'unfortunately', 'adverb', '', 'Leider habe ich keine Zeit.', "Unfortunately I don't have time."],
  ['zusammen', 'together', 'adverb', '', 'Wir lernen zusammen.', 'We study together.'],
  ['weil', 'because', 'conjunction', '', 'Ich bleibe zu Hause, weil ich krank bin.', "I'm staying home because I'm sick.", 'Subordinate clause → verb at the end.'],
  ['dass', 'that', 'conjunction', '', 'Ich glaube, dass er recht hat.', 'I think that he is right.', 'Subordinate clause → verb at the end.'],
  ['wenn', 'if; when(ever)', 'conjunction', '', 'Wenn es regnet, bleibe ich zu Hause.', 'If it rains, I stay at home.'],
  ['aber', 'but', 'conjunction', '', 'Das Auto ist schön, aber teuer.', 'The car is nice but expensive.'],
  ['warum', 'why', 'adverb', '', 'Warum lernst du Deutsch?', 'Why are you learning German?'],
  ['woher', 'where from', 'adverb', '', 'Woher kommst du?', 'Where are you from?'],
  ['wohin', 'where to', 'adverb', '', 'Wohin fährst du im Urlaub?', 'Where are you going on holiday?'],
  ['mit', 'with; by (transport)', 'preposition', '+ Dativ', 'Ich fahre mit dem Zug.', "I'm going by train."],
  ['für', 'for', 'preposition', '+ Akkusativ', 'Das ist für dich.', "That's for you."],
  ['ohne', 'without', 'preposition', '+ Akkusativ', 'Kaffee ohne Zucker, bitte.', 'Coffee without sugar, please.'],
  ['nach', 'after; to (places)', 'preposition', '+ Dativ', 'Nach der Arbeit gehe ich einkaufen.', 'After work I go shopping.'],
  ['seit', 'since, for (time)', 'preposition', '+ Dativ', 'Ich wohne seit zwei Jahren hier.', "I've been living here for two years."],
];
