import type { VerbRow } from './grundwortschatz';

/** Strong & irregular verbs beyond the A1 list: [infinitive, meaning, Stammformen, example, translation, notes?] */
export const STRONG_VERBS: VerbRow[] = [
  ['beginnen', 'to begin', 'beginnt · begann · hat begonnen', 'Der Kurs hat gestern begonnen.', 'The course began yesterday.'],
  ['bitten', 'to ask (for), to request', 'bittet · bat · hat gebeten', 'Ich habe ihn um Hilfe gebeten.', 'I asked him for help.', 'bitten um + Akk. ≠ beten (to pray).'],
  ['bieten', 'to offer', 'bietet · bot · hat geboten', 'Die Firma hat mir einen Job geboten.', 'The company offered me a job.'],
  ['binden', 'to tie, to bind', 'bindet · band · hat gebunden', 'Er hat die Schuhe gebunden.', 'He tied his shoes.'],
  ['bringen', 'to bring', 'bringt · brachte · hat gebracht', 'Kannst du mir ein Glas Wasser bringen?', 'Can you bring me a glass of water?', 'Mixed verb: -te ending but vowel change.'],
  ['empfehlen', 'to recommend', 'empfiehlt · empfahl · hat empfohlen', 'Kannst du mir ein Restaurant empfehlen?', 'Can you recommend a restaurant?'],
  ['fallen', 'to fall', 'fällt · fiel · ist gefallen', 'Das Glas ist vom Tisch gefallen.', 'The glass fell off the table.'],
  ['fangen', 'to catch', 'fängt · fing · hat gefangen', 'Die Katze hat eine Maus gefangen.', 'The cat caught a mouse.'],
  ['fliegen', 'to fly', 'fliegt · flog · ist geflogen', 'Wir sind nach Lissabon geflogen.', 'We flew to Lisbon.'],
  ['fließen', 'to flow', 'fließt · floss · ist geflossen', 'Der Rhein fließt durch Köln.', 'The Rhine flows through Cologne.'],
  ['frieren', 'to freeze, to be cold', 'friert · fror · hat gefroren', 'Ich friere, mach bitte das Fenster zu.', "I'm freezing, please close the window."],
  ['genießen', 'to enjoy', 'genießt · genoss · hat genossen', 'Wir haben den Urlaub sehr genossen.', 'We really enjoyed the holiday.'],
  ['geschehen', 'to happen', 'geschieht · geschah · ist geschehen', 'Was ist hier geschehen?', 'What happened here?'],
  ['gewinnen', 'to win', 'gewinnt · gewann · hat gewonnen', 'Unsere Mannschaft hat gewonnen!', 'Our team won!'],
  ['gießen', 'to pour; to water', 'gießt · goss · hat gegossen', 'Hast du die Blumen gegossen?', 'Did you water the flowers?'],
  ['halten', 'to hold; to stop', 'hält · hielt · hat gehalten', 'Der Bus hält direkt vor dem Haus.', 'The bus stops right in front of the house.', 'halten von = to think of: Was hältst du davon?'],
  ['hängen', 'to hang (be hanging)', 'hängt · hing · hat gehangen', 'Das Bild hat lange an der Wand gehangen.', 'The picture hung on the wall for a long time.', 'Transitive (to hang sth.) is weak: hängte · hat gehängt.'],
  ['heißen', 'to be called; to mean', 'heißt · hieß · hat geheißen', 'Wie heißt das auf Deutsch?', 'What is that called in German?'],
  ['laden', 'to load; to charge', 'lädt · lud · hat geladen', 'Ich habe mein Handy über Nacht geladen.', 'I charged my phone overnight.'],
  ['laufen', 'to run; to walk', 'läuft · lief · ist gelaufen', 'Ich bin heute zehn Kilometer gelaufen.', 'I ran ten kilometres today.', 'Also: Was läuft im Kino? (What\'s on?)'],
  ['leiden', 'to suffer', 'leidet · litt · hat gelitten', 'Er leidet unter Kopfschmerzen.', 'He suffers from headaches.'],
  ['leihen', 'to lend; to borrow', 'leiht · lieh · hat geliehen', 'Kannst du mir dein Fahrrad leihen?', 'Can you lend me your bike?', 'sich etwas leihen = to borrow.'],
  ['liegen', 'to lie (be lying)', 'liegt · lag · hat gelegen', 'Das Handy liegt auf dem Sofa.', 'The phone is lying on the sofa.', 'Southern German/Austrian: ist gelegen. Wo? → Dativ.'],
  ['lügen', 'to lie (tell lies)', 'lügt · log · hat gelogen', 'Du hast mich angelogen!', 'You lied to me!'],
  ['nennen', 'to name, to call', 'nennt · nannte · hat genannt', 'Alle nennen ihn Max.', 'Everybody calls him Max.', 'Mixed verb.'],
  ['raten', 'to guess; to advise', 'rät · riet · hat geraten', 'Rate mal, wen ich getroffen habe!', 'Guess who I met!'],
  ['rennen', 'to run, to race', 'rennt · rannte · ist gerannt', 'Die Kinder sind zum Spielplatz gerannt.', 'The children ran to the playground.', 'Mixed verb.'],
  ['riechen', 'to smell', 'riecht · roch · hat gerochen', 'Hier riecht es nach frischem Brot.', 'It smells of fresh bread here.'],
  ['rufen', 'to call, to shout', 'ruft · rief · hat gerufen', 'Ruf bitte ein Taxi!', 'Please call a taxi!'],
  ['scheinen', 'to shine; to seem', 'scheint · schien · hat geschienen', 'Gestern hat den ganzen Tag die Sonne geschienen.', 'Yesterday the sun shone all day.'],
  ['schlagen', 'to hit, to beat', 'schlägt · schlug · hat geschlagen', 'Bayern hat Dortmund drei zu eins geschlagen.', 'Bayern beat Dortmund three to one.'],
  ['schließen', 'to close, to shut', 'schließt · schloss · hat geschlossen', 'Hast du die Tür geschlossen?', 'Did you close the door?'],
  ['schneiden', 'to cut', 'schneidet · schnitt · hat geschnitten', 'Ich habe mich in den Finger geschnitten.', 'I cut my finger.'],
  ['schweigen', 'to be silent', 'schweigt · schwieg · hat geschwiegen', 'Er hat die ganze Zeit geschwiegen.', 'He was silent the whole time.'],
  ['schwimmen', 'to swim', 'schwimmt · schwamm · ist geschwommen', 'Wir sind im See geschwommen.', 'We swam in the lake.'],
  ['singen', 'to sing', 'singt · sang · hat gesungen', 'Sie hat auf der Hochzeit gesungen.', 'She sang at the wedding.'],
  ['sitzen', 'to sit (be sitting)', 'sitzt · saß · hat gesessen', 'Wir haben stundenlang im Café gesessen.', 'We sat in the café for hours.', 'Southern German/Austrian: ist gesessen. Wo? → Dativ.'],
  ['springen', 'to jump', 'springt · sprang · ist gesprungen', 'Der Hund ist über den Zaun gesprungen.', 'The dog jumped over the fence.'],
  ['stehen', 'to stand', 'steht · stand · hat gestanden', 'Das Auto steht vor der Tür.', 'The car is (parked) in front of the door.', 'Also: Das steht dir gut! (That suits you!)'],
  ['stehlen', 'to steal', 'stiehlt · stahl · hat gestohlen', 'Man hat mir das Fahrrad gestohlen.', 'My bike was stolen.'],
  ['steigen', 'to climb; to rise', 'steigt · stieg · ist gestiegen', 'Die Preise sind stark gestiegen.', 'Prices have risen sharply.', 'einsteigen / aussteigen = to get on / off.'],
  ['sterben', 'to die', 'stirbt · starb · ist gestorben', 'Mein Großvater ist letztes Jahr gestorben.', 'My grandfather died last year.'],
  ['streiten', 'to argue, to quarrel', 'streitet · stritt · hat gestritten', 'Die Geschwister streiten sich ständig.', 'The siblings argue all the time.'],
  ['tragen', 'to carry; to wear', 'trägt · trug · hat getragen', 'Sie trägt heute ein rotes Kleid.', "She's wearing a red dress today."],
  ['treffen', 'to meet; to hit', 'trifft · traf · hat getroffen', 'Ich habe zufällig meinen Lehrer getroffen.', 'I happened to meet my teacher.'],
  ['tun', 'to do', 'tut · tat · hat getan', 'Was kann ich für Sie tun?', 'What can I do for you?', 'Es tut mir leid = I am sorry.'],
  ['vergessen', 'to forget', 'vergisst · vergaß · hat vergessen', 'Ich habe meinen Schirm vergessen.', 'I forgot my umbrella.'],
  ['vergleichen', 'to compare', 'vergleicht · verglich · hat verglichen', 'Vergleich die Preise, bevor du kaufst!', 'Compare prices before you buy!'],
  ['verlieren', 'to lose', 'verliert · verlor · hat verloren', 'Ich habe meinen Schlüssel verloren.', "I've lost my key."],
  ['verbieten', 'to forbid', 'verbietet · verbot · hat verboten', 'Rauchen ist hier verboten.', 'Smoking is forbidden here.'],
  ['wachsen', 'to grow', 'wächst · wuchs · ist gewachsen', 'Der Junge ist dieses Jahr zehn Zentimeter gewachsen.', 'The boy has grown ten centimetres this year.'],
  ['waschen', 'to wash', 'wäscht · wusch · hat gewaschen', 'Ich habe die Wäsche schon gewaschen.', "I've already done the laundry."],
  ['werfen', 'to throw', 'wirft · warf · hat geworfen', 'Wirf den Müll bitte in den Eimer!', 'Please throw the rubbish in the bin!'],
  ['ziehen', 'to pull; to move (house)', 'zieht · zog · hat gezogen', 'Wir sind nach Leipzig gezogen.', 'We moved to Leipzig.', 'Moving house uses sein: ist gezogen.'],
  ['backen', 'to bake', 'backt · backte · hat gebacken', 'Oma hat einen Apfelkuchen gebacken.', 'Grandma baked an apple cake.', 'Older present form: bäckt.'],
  ['braten', 'to fry, to roast', 'brät · briet · hat gebraten', 'Er brät das Fleisch in der Pfanne.', 'He is frying the meat in the pan.'],
  ['erschrecken', 'to get a fright', 'erschrickt · erschrak · ist erschrocken', 'Ich bin furchtbar erschrocken!', 'I got a terrible fright!', 'To frighten someone is weak: erschreckte · hat erschreckt.'],
  ['gelingen', 'to succeed (impersonal)', 'gelingt · gelang · ist gelungen', 'Der Kuchen ist dir gut gelungen!', 'Your cake turned out well!', 'The thing succeeds; the person is Dativ.'],
  ['reiten', 'to ride (a horse)', 'reitet · ritt · ist geritten', 'Als Kind bin ich oft geritten.', 'As a child I often went riding.'],
  ['schieben', 'to push', 'schiebt · schob · hat geschoben', 'Wir haben das Auto in die Garage geschoben.', 'We pushed the car into the garage.'],
  ['sinken', 'to sink; to fall', 'sinkt · sank · ist gesunken', 'Die Temperaturen sind unter null gesunken.', 'Temperatures have fallen below zero.'],
  ['sprechen', 'to speak', 'spricht · sprach · hat gesprochen', 'Wir haben lange über die Zukunft gesprochen.', 'We talked about the future for a long time.'],
  ['treten', 'to step; to kick', 'tritt · trat · ist getreten', 'Er ist in eine Pfütze getreten.', 'He stepped in a puddle.', 'Kicking something uses haben: Er hat den Ball getreten.'],
  ['weisen', 'to point, to show', 'weist · wies · hat gewiesen', 'Er hat mir den Weg gewiesen.', 'He showed me the way.'],
];

/** Cloze sentences for cases, prepositions and word order: [text, extra] */
export const CLOZE_CASES: [string, string][] = [
  ['Ich fahre mit {{c1::dem::der Bus}} Bus zur Arbeit.', 'mit + Dativ → der Bus wird zu dem Bus.'],
  ['Das Geschenk ist für {{c1::den::der Vater}} Vater.', 'für + Akkusativ → den (maskulin).'],
  ['Wir gehen durch {{c1::den::der Park}} Park.', 'durch + Akkusativ → den.'],
  ['Ich komme gerade aus {{c1::der::die Bäckerei}} Bäckerei.', 'aus + Dativ → die wird zu der (feminin).'],
  ['Sie wohnt bei {{c1::ihrer::ihre Schwester}} Schwester.', 'bei + Dativ → ihrer (feminin).'],
  ['Seit {{c1::einem::ein Jahr}} Jahr lerne ich Deutsch.', 'seit + Dativ → einem (neutrum).'],
  ['Nach {{c1::dem::das Essen}} Essen trinken wir einen Kaffee.', 'nach + Dativ → dem (neutrum).'],
  ['Ich gehe ohne {{c1::meinen::mein Regenschirm}} Regenschirm los.', 'ohne + Akkusativ → meinen (maskulin).'],
  ['Das Buch liegt auf {{c1::dem::der Tisch}} Tisch.', 'Wo? → Dativ. Position (liegen) → dem.'],
  ['Ich lege das Buch auf {{c1::den::der Tisch}} Tisch.', 'Wohin? → Akkusativ. Movement (legen) → den.'],
  ['Wir sitzen in {{c1::der::die Küche}} Küche.', 'Wo? → Dativ → der (feminin).'],
  ['Ich gehe in {{c1::die::die Küche}} Küche.', 'Wohin? → Akkusativ → die bleibt die.'],
  ['Die Katze schläft unter {{c1::dem::das Bett}} Bett.', 'Wo? → Dativ → dem.'],
  ['Der Hund kriecht unter {{c1::das::das Bett}} Bett.', 'Wohin? → Akkusativ → das.'],
  ['Das Bild hängt an {{c1::der::die Wand}} Wand.', 'Wo? → Dativ → der.'],
  ['Ich hänge das Bild an {{c1::die::die Wand}} Wand.', 'Wohin? → Akkusativ → die.'],
  ['Die Apotheke ist neben {{c1::der::die Bank}} Bank.', 'Wo? → Dativ → der.'],
  ['Stell die Milch bitte in {{c1::den::der Kühlschrank}} Kühlschrank!', 'Wohin? → Akkusativ → den.'],
  ['Wegen {{c1::des::das Wetter}} Wetters bleiben wir zu Hause.', 'wegen + Genitiv → des Wetters (-s!).'],
  ['Trotz {{c1::des::der Regen}} Regens machen wir einen Ausflug.', 'trotz + Genitiv → des Regens.'],
  ['Ich gebe {{c1::dem::der Mann}} Mann das Buch.', 'geben: who receives it → Dativ → dem.'],
  ['Ich helfe {{c1::meiner::meine Mutter}} Mutter in der Küche.', 'helfen + Dativ → meiner.'],
  ['Das Auto gehört {{c1::meinem::mein Bruder}} Bruder.', 'gehören + Dativ → meinem.'],
  ['Hast du {{c1::einen::ein Stift}} Stift für mich?', 'haben + Akkusativ → einen (maskulin).'],
  ['Ich gehe morgen {{c1::zum::zu + dem}} Arzt.', 'zu + dem → zum.'],
  ['Wir fahren mit dem Rad {{c1::zur::zu + der}} Arbeit.', 'zu + der → zur.'],
  ['Heute Abend sind wir {{c1::im::in + dem}} Kino.', 'Wo? in + dem → im.'],
  ['Gehen wir heute Abend {{c1::ins::in + das}} Kino?', 'Wohin? in + das → ins.'],
  ['Er wartet {{c1::am::an + dem}} Bahnhof auf mich.', 'an + dem → am.'],
  ['Ich komme gerade {{c1::vom::von + dem}} Supermarkt.', 'von + dem → vom.'],
  ['Wir spielen mit {{c1::den::die Kinder (Pl.)}} Kindern im Park.', 'Dativ Plural: die → den, and the noun gets -n: Kindern.'],
  ['Wir warten auf {{c1::den::der Zug}} Zug.', 'warten auf + Akkusativ → den.'],
  ['Ich freue mich auf {{c1::das::das Wochenende}} Wochenende.', 'sich freuen auf + Akkusativ (future) → das.'],
  ['Ich interessiere mich für {{c1::die::die Geschichte}} Geschichte.', 'sich interessieren für + Akkusativ → die.'],
  ['Sie hat Angst vor {{c1::dem::der Hund}} Hund.', 'Angst haben vor + Dativ → dem.'],
  ['Wir sprechen über {{c1::den::der Film}} Film.', 'sprechen über + Akkusativ → den.'],
  ['Das ist das Auto {{c1::meines::mein Vater}} Vaters.', 'Genitiv (whose?) → meines Vaters.'],
  ['Ich bleibe heute zu Hause, weil ich krank {{c1::bin}}.', 'weil → the conjugated verb goes to the end.'],
  ['Ich weiß nicht, ob er morgen {{c1::kommt::kommen}}.', 'ob → verb at the end.'],
  ['Morgen {{c1::fahre::fahren}} ich nach Hamburg.', 'Verb always in position 2 — even when the sentence starts with “Morgen”.'],
  ['Ich {{c1::stehe}} jeden Tag um sechs Uhr {{c2::auf}}.', 'aufstehen is separable: the prefix goes to the end.'],
  ['Gestern {{c1::bin}} ich ins Kino {{c2::gegangen}}.', 'Perfekt of gehen → sein + gegangen (movement).'],
  ['Wir {{c1::haben}} am Samstag lange {{c2::geschlafen}}.', 'Perfekt of schlafen → haben + geschlafen.'],
  ['Wenn ich Zeit habe, {{c1::gehe::gehen}} ich ins Fitnessstudio.', 'Subordinate clause first → main clause starts with the verb.'],
];

/** Everyday phrases: [German, meaning, note?] */
export const PHRASES: [string, string, string?][] = [
  ["Wie geht's?", 'How are you? (informal)'],
  ['Wie geht es Ihnen?', 'How are you? (formal)'],
  ["Mir geht's gut, danke.", "I'm fine, thanks."],
  ['Freut mich!', 'Nice to meet you!'],
  ['Entschuldigung!', 'Excuse me! / Sorry!'],
  ['Wie bitte?', 'Pardon? / Sorry, what did you say?'],
  ['Können Sie das bitte wiederholen?', 'Could you repeat that, please?'],
  ['Sprechen Sie bitte etwas langsamer.', 'Please speak a little more slowly.'],
  ['Was bedeutet das?', 'What does that mean?'],
  ['Wie sagt man das auf Deutsch?', 'How do you say that in German?'],
  ['Ich verstehe das nicht.', "I don't understand that."],
  ['Keine Ahnung.', 'No idea.'],
  ['Das macht nichts.', "Never mind. / That doesn't matter."],
  ['Kein Problem!', 'No problem!'],
  ['Gern geschehen!', "You're welcome!"],
  ['Bis später!', 'See you later!'],
  ['Schönes Wochenende!', 'Have a nice weekend!'],
  ['Gute Besserung!', 'Get well soon!'],
  ['Viel Glück!', 'Good luck!'],
  ['Herzlichen Glückwunsch zum Geburtstag!', 'Happy birthday!'],
  ['Prost!', 'Cheers!'],
  ['Guten Appetit!', 'Enjoy your meal!'],
  ['Ich hätte gern einen Kaffee.', "I'd like a coffee, please.", 'Polite ordering: Ich hätte gern … / Ich möchte …'],
  ['Die Rechnung, bitte.', 'The bill, please.'],
  ['Zusammen oder getrennt?', 'Together or separately? (paying)'],
  ['Stimmt so.', 'Keep the change.'],
  ['Was kostet das?', 'How much does that cost?'],
  ['Wo ist die Toilette?', 'Where is the toilet?'],
  ['Wie komme ich zum Bahnhof?', 'How do I get to the station?'],
  ['Geradeaus und dann links.', 'Straight ahead and then left.'],
  ['Ist hier noch frei?', 'Is this seat free?'],
  ['Ich bin gleich wieder da.', "I'll be right back."],
  ['Das ist mir egal.', "I don't mind. / It's all the same to me."],
  ['Das kommt darauf an.', 'That depends.'],
  ['Na klar!', 'Of course!'],
  ['Genau!', 'Exactly!'],
  ['Ich habe keine Lust.', "I don't feel like it."],
  ['Hast du Lust, ins Kino zu gehen?', 'Do you feel like going to the cinema?'],
  ['Was ist los?', "What's wrong? / What's going on?"],
  ['Alles klar?', 'Everything OK? / Got it?'],
  ['Ich drücke dir die Daumen!', "I'll keep my fingers crossed for you!", 'Literally: I press my thumbs for you.'],
  ['Da hast du recht.', "You're right about that."],
  ['Ich verstehe nur Bahnhof.', "It's all Greek to me.", 'Idiom — literally: I only understand “train station”.'],
  ['Das ist nicht mein Bier.', 'That is not my problem.', 'Idiom — literally: that is not my beer.'],
  ['Schwein gehabt!', 'Lucky you! / That was lucky!', 'Idiom — literally: had a pig.'],
  ['Tomaten auf den Augen haben', 'to not see what is obvious', 'Idiom — literally: to have tomatoes on your eyes.'],
  ['Feierabend!', 'Quitting time! (end of the working day)'],
  ['Tschüss!', 'Bye!'],
  ['Auf Wiedersehen!', 'Goodbye! (formal)'],
  ['Moin!', 'Hi! (Northern Germany, any time of day)'],
  ['Servus!', 'Hi! / Bye! (Southern Germany & Austria)'],
  ['Grüß Gott!', 'Hello! (Bavaria & Austria)'],
];
